name: Deploy Landing Zone
on: [push]

permissions:
  id-token: write
  contents: read

env:
  MGMT_ACCOUNT_ID: ${{ secrets.MGMT_ACCOUNT_ID }}
  LOG_ARCHIVE_ACCOUNT_ID: ${{ secrets.LOG_ARCHIVE_ACCOUNT_ID }}
  NETWORK_ACCOUNT_ID: ${{ secrets.NETWORK_ACCOUNT_ID }}
  WORKLOAD_ACCOUNT_ID: ${{ secrets.WORKLOAD_ACCOUNT_ID }}
  ORG_ROOT_ID: ${{ secrets.ORG_ROOT_ID }} # <--- FUEL FOR THE ENGINE

jobs:
  deploy-mgmt:
    name: 1. Management
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.MGMT_ROLE_ARN }}
          aws-region: us-east-1
      - name: Deploy
        run: |
          pip install -r requirements.txt
          npx cdk deploy OrgGovernanceStack --require-approval never

  deploy-security:
    name: 2. Security
    needs: deploy-mgmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LOG_ARCHIVE_ROLE_ARN }}
          aws-region: us-east-1
      - name: Deploy
        run: |
          pip install -r requirements.txt
          npx cdk deploy LogArchiveCentralStack --require-approval never

  deploy-mumbai:
    name: 3. Networking Mumbai
    needs: deploy-security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.NETWORK_ROLE_ARN }}
          aws-region: ap-south-1
      - name: Deploy
        run: |
          pip install -r requirements.txt
          npx cdk deploy GlobalControlNetworkMumbai --require-approval never

  deploy-workload:
    name: 4. Workload Platform
    needs: deploy-mumbai
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.WORKLOAD_ROLE_ARN }}
          aws-region: us-east-1
      - name: Deploy
        run: |
          pip install -r requirements.txt
          npx cdk deploy WorkloadSharedNetwork WorkloadAccountBaseline --require-approval never
